### ISSUE TITLE
learn doctor errors

### ISSUE THREAD

**Issue by saltillokid11** [learn-co/learn-ide#287]
`[14:18:52] code                                                                                                                                                               
// ♥ learn doctor                                                                                                                                                             
Preparing...                                                                                                                                                                  
Getting latest environment environment setup data from Learn...                                                                                                               
Homebrew.../usr/local/rvm/gems/ruby-2.2.3/gems/learn-doctor-1.0.3/lib/learn_doctor/health_check/step_checker.rb:29:in ``': Text file busy - /tmp/Homebrew20160901-16750-1way1s
j (Errno::ETXTBSY)`

```
    from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-doctor-1.0.3/lib/learn_doctor/health_check/step_checker.rb:29:in `run_check_for_step'                                  
    from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-doctor-1.0.3/lib/learn_doctor/health_check/step_checker.rb:14:in `execute'                                             
    from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-doctor-1.0.3/lib/learn_doctor/health_check.rb:42:in `block in run_checks!'                                             
    from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-doctor-1.0.3/lib/learn_doctor/health_check.rb:41:in `each'                                                             
    from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-doctor-1.0.3/lib/learn_doctor/health_check.rb:41:in `run_checks!'                                                      
    from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-doctor-1.0.3/lib/learn_doctor/health_check.rb:24:in `diagnose'                                                         
    from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-doctor-1.0.3/lib/learn_doctor/health_check.rb:11:in `diagnose'                                                         
    from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-doctor-1.0.3/bin/learn-doctor:12:in `<top (required)>'                                                                 
    from /usr/local/rvm/gems/ruby-2.2.3/bin/learn-doctor:23:in `load'                                                                                                     
    from /usr/local/rvm/gems/ruby-2.2.3/bin/learn-doctor:23:in `<main>'                                                                                                   
    from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'                                                                                            
    from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'  
```

**Comment by drewprice** [comment]
gem related
