### ISSUE TITLE
Uncaught TypeError: Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by adamjonas** [learn-co/learn-ide#360]
[Enter steps to reproduce below:]

1. Lose internet.
2. Get internet back.
3. Obsessively hit the reconnect button.

![screen shot 2016-11-02 at 8 28 19 pm](https://cloud.githubusercontent.com/assets/755825/19952444/b1ad5950-a13b-11e6-88b3-9749b134fed3.png)

**Atom Version**: 2.0.0-beta3
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.1
**Thrown From**: [learn-ide](https://github.com/learn-co/learn-ide) package, v2.0.0-beta3

### Stack Trace

Uncaught TypeError: Cannot read property 'log' of undefined

```
At /Users/jonas/Downloads/Learn IDE Beta.app/Contents/Resources/app.asar/node_modules/node-ipc/dao/client.js:127

TypeError: Cannot read property 'log' of undefined
    at Socket.<anonymous> (/Users/jonas/Downloads/Learn IDE Beta.app/Contents/Resources/app.asar/node_modules/node-ipc/dao/client.js:127:19)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at onwriteError (_stream_writable.js:313:10)
    at onwrite (_stream_writable.js:331:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:450:13)
    at Socket._destroy (net.js:459:5)
    at Socket._writeGeneric (net.js:648:10)
    at Socket._write (net.js:700:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Socket.Writable.write (_stream_writable.js:215:11)
    at Socket.write (net.js:626:40)
    at Client.emit (/Users/jonas/Downloads/Learn IDE Beta.app/Contents/Resources/app.asar/node_modules/node-ipc/dao/client.js:45:21)
    at SingleSocket.close (/Users/jonas/Downloads/Learn IDE Beta.app/Contents/Resources/app.asar/node_modules/single-socket/lib/single-socket.js:67:19)
    at Terminal.module.exports.Terminal.reset (/Users/jonas/Downloads/Learn IDE Beta.app/Contents/Resources/app.asar/node_modules/learn-ide/lib/terminal.js:66:19)
    at HTMLDivElement.<anonymous> (/Users/jonas/Downloads/Learn IDE Beta.app/Contents/Resources/app.asar/node_modules/learn-ide/lib/views/status.js:69:33)
```

### Commands

```
     -5:41.6.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -5:20.1.0 learn-ide:save (atom-text-editor.editor.is-focused)
  4x -3:37.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:36.2.0 learn-ide:save (atom-text-editor.editor.is-focused)
     -3:35.1.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:34.9.0 learn-ide:save (atom-text-editor.editor.is-focused)
     -3:32 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:30.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:30.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:30.4.0 tree-view:add-file (atom-text-editor.editor.is-focused)
  2x -3:25.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:24.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:03.8.0 core:close (atom-text-editor.editor.is-focused)
  2x -1:55.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:53.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:50.8.0 learn-ide:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment"
    ]
  },
  "learn-ide": {
    "oauthToken": "8def7bfa10b497267c50ee8791a2950bf90e65aadd6b3a59fd82656d9eedb1ea",
    "vmPort": 3007
  }
}
```

### Installed Packages

```coffee
# User
integrated-learn-environment, v1.9.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
update-package-dependencies, v0.10.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)
learn-ide, v2.0.0-beta3 (active)
learn-ide-tree, v1.0.6 (active)

# Dev
No dev packages
```

**Comment by drewprice** [comment]
@joshrowley I was seeing this as well earlier today

**Comment by joshrowley** [comment]
maybe, i'll look into it, thanks for the detailed report @adamjonas

**Comment by adamjonas** [comment]
tada
