### ISSUE TITLE
Uncaught Error: Invalid UTF-8 detected for javascript-logging-lab's package.json

### ISSUE THREAD

**Issue by The-Alchemist** [learn-co/learn-ide#367]
### How to Reproduce

1. Open https://learn.co/tracks/bootcamp-prep/javascript-fundamentals/javascript-basics/javascript-logging-lab
2. Run ``vim package.json``

**Atom Version**: 1.9.0-2edf93d
**System**: Mac OS X 10.11.6
**Thrown From**: [integrated-learn-environment](https://github.com/flatiron-labs/integrated-learn-environment) package, v1.9.0

### Stack Trace

Uncaught Error: Invalid UTF-8 detected

```
At /Users/alchemist/.atom/packages/integrated-learn-environment/node_modules/utf8/utf8.js:194

Error: Invalid UTF-8 detected
    at Error (native)
    at decodeSymbol (/Users/alchemist/.atom/packages/integrated-learn-environment/node_modules/utf8/utf8.js:194:9)
    at Object.utf8decode [as decode] (/Users/alchemist/.atom/packages/integrated-learn-environment/node_modules/utf8/utf8.js:206:33)
    at Terminal.<anonymous> (/Users/alchemist/.atom/packages/integrated-learn-environment/lib/views/terminal.coffee:52:24)
    at emitOne (events.js:77:13)
    at Terminal.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/Users/alchemist/.atom/packages/integrated-learn-environment/lib/models/terminal.coffee:22:12)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -6:36.4.0 learn-ide:reset (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:18.5.0 learn-ide:resync (span.name.icon.icon-file-directory)
     -5:10.8.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:45.5.0 application:update-ile (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Installed Packages

```coffee
# User
integrated-learn-environment, v1.9.0

# Dev
No dev packages
```

## Screenshot

![image](https://cloud.githubusercontent.com/assets/812287/20325913/920414fe-ab54-11e6-8dd7-03bb7b5d007d.png)

**Comment by aubuchon44** [comment]
same problem here also.

**Comment by drewprice** [comment]
Thanks for reporting—this is a known issue. The current terminal emulator (or something about the way we're using it) breaks with any text editor, regardless of the file it attempts to open. Closing and moving to #393
