### ISSUE TITLE
fresh install on Windows 10 gives "cannot find module 'menu'" and "cannot find module 'browser-window'"

### ISSUE THREAD

**Issue by The-Alchemist** [learn-co/learn-ide#390]
# info
[Enter steps to reproduce below:]

1. Just install from scratch and start

**Atom Version**: 2.2.1
**Electron Version**: 1.3.6
**System**: Microsoft Windows 10 Pro
**Thrown From**: [learn-ide](https://github.com/learn-co/learn-ide) package, v2.2.1

### Stack Trace

Failed to activate the learn-ide package

```
At Cannot find module 'menu'
Error: Cannot find module 'menu'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at EventEmitter.<anonymous> (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\api\web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

Error: Cannot find module 'menu'
Error: Cannot find module 'menu'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at EventEmitter.<anonymous> (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\api\web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\renderer\api\remote.js:210:13)
    at Object.exports.require (C:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\renderer\api\remote.js:297:10)
    at Object.<anonymous> (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide\lib\views\terminal.js:13:17)
    at Object.<anonymous> (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide\lib\views\terminal.js:366:4)
    at Module._compile (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide\lib\learn-ide.js:10:18)
    at Object.<anonymous> (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide\lib\learn-ide.js:247:4)
    at Module._compile (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:741:27)
    at Package.module.exports.Package.activateNow (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:174:16)
    at J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:157:32
    at Package.module.exports.Package.measure (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:92:15)
    at J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:150:26
    at Package.module.exports.Package.activate (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package-manager.js:548:21)
    at J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (J:\Users\noodlez-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package-manager.js:524:19)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
update-package-dependencies, v0.10.0 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)
learn-ide, v2.2.1 (inactive)
learn-ide-tree, v1.0.17 (inactive)

# Dev
No dev packages
```

# error 1

```
Cannot find module 'menu'
Error: Cannot find module 'menu'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at EventEmitter.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\api\web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
Hide Stack Trace
Error: Cannot find module 'menu'
Error: Cannot find module 'menu'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at EventEmitter.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\api\web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\renderer\api\remote.js:210:13)
    at Object.exports.require (C:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\renderer\api\remote.js:297:10)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide\lib\views\terminal.js:13:17)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide\lib\views\terminal.js:366:4)
    at Module._compile (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide\lib\learn-ide.js:10:18)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide\lib\learn-ide.js:247:4)
    at Module._compile (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:741:27)
    at Package.module.exports.Package.activateNow (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:174:16)
    at J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:157:32
    at Package.module.exports.Package.measure (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:92:15)
    at J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:150:26
    at Package.module.exports.Package.activate (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package-manager.js:548:21)
    at J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\package-manager.js:524:19)
```
# error 2
```
Cannot find module 'browser-window'
Error: Cannot find module 'browser-window'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at EventEmitter.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\api\web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
Hide Stack Trace
Error: Cannot find module 'browser-window'
Error: Cannot find module 'browser-window'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at EventEmitter.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\browser\api\web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\renderer\api\remote.js:210:13)
    at Object.exports.require (C:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\electron.asar\renderer\api\remote.js:297:10)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\web-window.js:10:26)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\web-window.js:52:4)
    at Module._compile (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\custom-commands.js:10:15)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\custom-commands.js:48:4)
    at Module._compile (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\initializer.js:18:26)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\initializer.js:248:4)
    at Module._compile (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (J:\Users\some-user\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide-tree\lib\main.js:12:22)
```

**Comment by The-Alchemist** [comment]
I have a weird Windows 10 install (my account profile is on another drive), and I couldn't reproduce this on a fresh, "regular" user account.

**Comment by drewprice** [comment]
Going to close, as many of the things related to these errors have changed quite a bit since then (now at v2.4.0), and because of an inability to reproduce.
