### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by Alya12** [learn-co/learn-ide#412]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 2.4.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [learn-ide](https://github.com/learn-co/learn-ide) package 2.4.0

### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of undefined

```
At C:\Users\Aidab\AppData\Local\learn_ide\app-2.4.0\resources\app.asar\node_modules\learn-term.js\src\term.js:1413

TypeError: Cannot set property 'innerHTML' of undefined
    at TerminalWrapper.Terminal.refresh (/app.asar/node_modules/learn-term.js/src/term.js:1413:32)
    at TerminalWrapper.Terminal.write (/app.asar/node_modules/learn-term.js/src/term.js:2557:8)
    at TerminalWrapper.module.exports.TerminalWrapper.write (/app.asar/node_modules/learn-ide/lib/views/terminal-wrapper.js:19:39)
    at /app.asar/node_modules/learn-ide/lib/views/terminal.js:129:40)
    at emitOne (events.js:96:13)
    at Terminal.emit (events.js:188:7)
    at /app.asar/node_modules/learn-ide/lib/terminal.js:45:26)
    at emitOne (events.js:96:13)
    at PageBus.emit (events.js:188:7)
    at /app.asar/node_modules/page-bus/index.js:21:44
```

### Commands

```
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
```

**Comment by Alya12** [comment]
When I open lesson it would not open and rather shows me that window. What should I do?

**Comment by drewprice** [comment]
@Alya12 the best thing to do to get around this is to reach out for support on learn, we will be addressing the route issue in a future release. Thanks for reporting!

**Comment by PCGeekBrain** [comment]
Issue happened again on windows 10
