### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by chemturion** [learn-co/learn-ide#423]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [learn-ide](https://github.com/learn-co/learn-ide) package 2.4.2

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/kelton/.atom/packages/learn-ide/node_modules/learn-term.js/src/term.js:1306

TypeError: Cannot read property '0' of undefined
    at TerminalWrapper.Terminal.refresh (/packages/learn-ide/node_modules/learn-term.js/src/term.js:1306:18)
    at TerminalWrapper.Terminal._cursorBlink (/packages/learn-ide/node_modules/learn-term.js/src/term.js:1422:8)
    at _blinker (/packages/learn-ide/node_modules/learn-term.js/src/term.js:1439:10)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-syntax-light 0.4.6 
atom-runner 2.7.1 
autocomplete-ruby 0.2.6 
learn-ide 2.4.2 
learn-ide-material-ui 1.3.14 
learn-ide-tree 1.0.22 
linter 1.11.23 
linter-rubocop 1.1.0 
```

**Comment by drewprice** [comment]
This was addressed in #409 an will be released with v2.5 🎉
