### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTime' of undefined

### ISSUE THREAD

**Issue by kvignali** [learn-co/learn-ide#463]
/Users/kaitlinvignali/.atom/packages/learn-ide-tree/lib/tree-view.coffee:286
Hide Stack Trace
TypeError: Cannot read property 'getTime' of undefined
    at TreeView.<anonymous> (/Users/kaitlinvignali/.atom/packages/learn-ide-tree/lib/tree-view.coffee:286:32)
    at TreeView.module.exports.TreeView.updateRoots (/Users/kaitlinvignali/.atom/packages/learn-ide-tree/lib/tree-view.coffee:282:14)
    at /Users/kaitlinvignali/.atom/packages/learn-ide-tree/lib/tree-view.coffee:149:8
    at Function.module.exports.Emitter.simpleDispatch (/Users/kaitlinvignali/Downloads/Learn IDE.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/kaitlinvignali/Downloads/Learn IDE.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/Users/kaitlinvignali/Downloads/Learn IDE.app/Contents/Resources/app.asar/src/project.js:277:29)
    at Object.updateProject (/Users/kaitlinvignali/.atom/packages/learn-ide-tree/lib/nsync/atom-helper.coffee:59:18)
    at /Users/kaitlinvignali/.atom/packages/learn-ide-tree/lib/nsync/initializer.coffee:149:18
    at Emitter.module.exports.Emitter.emit (/Users/kaitlinvignali/.atom/packages/learn-ide-tree/node_modules/nsync-fs/node_modules/event-kit/lib/emitter.js:82:11)
    at Nsync.setPrimaryNode (/Users/kaitlinvignali/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:120:25)
    at init (/Users/kaitlinvignali/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/onmessage-strategies/init.js:6:9)
    at onmessage (/Users/kaitlinvignali/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/onmessage.js:47:12)
    at PageBus.<anonymous> (/Users/kaitlinvignali/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/connection.js:24:16)
    at emitOne (events.js:96:13)
    at PageBus.emit (events.js:188:7)
    at /Users/kaitlinvignali/.atom/packages/learn-ide-tree/node_modules/page-bus/index.js:21:44
The error was thrown from the learn-ide-tree package. This issue has already been reported.

**Comment by kvignali** [comment]
unable to see the file tree:

<img width="1054" alt="screen shot 2017-05-17 at 4 25 57 pm" src="https://cloud.githubusercontent.com/assets/2243896/26174567/d5a73f20-3b1d-11e7-93de-0342f54ee938.png">

**Comment by drewprice** [comment]
This has been around for a while 😕 https://github.com/learn-co/learn-ide-tree/issues/21

**Comment by drewprice** [comment]
Issue moved to [learn-co/learn-ide-tree #56](https://github.com/learn-co/learn-ide-tree/issues/56) via [**ZenHub**](https://www.zenhub.com/)
