### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reset' of undefined

### ISSUE THREAD

**Issue by kberba** [learn-co/learn-ide#496]
I was trying to open Learn IDE and load my code, but I was getting this error.  (Please let me know if I'm posting this incorrectly.. I've never submitted an issue before. Thank you!)

OS: Windows 10
Learn IDE: v2.5.2

# TypeError: Cannot read property 'reset' of undefined
`   at Connection.module.exports.Connection.reset (C:\Users\Karen\.atom\packages\learn-ide-tree\node_modules\nsync-fs\lib\connection.js:49:23)
    at Nsync.resetConnection (C:\Users\Karen\.atom\packages\learn-ide-tree\node_modules\nsync-fs\lib\nsync-fs.js:86:28)
    at atom-workspace.onResetConnection (file:///C:/Users/Karen/.atom/packages/learn-ide-tree/lib/nsync/initializer.coffee:121:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Karen\AppData\Local\learn_ide\app-2.4.2\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Karen\AppData\Local\learn_ide\app-2.4.2\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Karen\AppData\Local\learn_ide\app-2.4.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Karen\AppData\Local\learn_ide\app-2.4.2\resources\app.asar\src\atom-environment.js:1164:28)
    at EventEmitter.outerCallback (C:\Users\Karen\AppData\Local\learn_ide\app-2.4.2\resources\app.asar\src\application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)`

**Comment by drewprice** [comment]
Hey @kberba, thanks for reporting! Just a meta comment for now: this report is great. When the error notification appears, you can also (usually) use the "Create an issue..." button, which will provide a bit more context. If there was no button, then this is great.

It looks like this may have been related to reconnect... were there any messages about being disconnected? and if so, did you attempt to reconnect?

**Comment by kberba** [comment]
Hi @drewprice, thank you for your reply! There was a button, but when I tried clicking on it nothing was happening. I believe it was related to reconnecting, because I was attempting to reconnect and kept getting disconnected (and that's when the message appeared). There were messages about being disconnected, but that was the first time I've ever seen that error message before.
